name: publish

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ”¨ checkout
        uses: actions/checkout@v4

      - name: ğŸ”¨ Setup node 22
        uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'

      - name: ğŸ”¨ Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: ğŸ”¨ Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: ğŸ”¨ Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: ğŸ”¨ Install dependencies
        run: pnpm install

      - name: ğŸ”¨ Build project
        run: pnpm build

      - name: ğŸ”¨ Package library
        run: pnpm package

      - name: ğŸ”¨ publish library
        run: pnpm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
